rest/booking/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'booking'
urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path('', views.post_list, name='list_tables'),
    path('<int:number>/', views.table_detail, name='table_detail'),
    path('<int:number>/reservation/', views.table_reservation, name='table_reservation'),
    path('<int:number>/cancel_booking', views.cancel_booking, name='cancel_booking')
]

rest/rest/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('booking/', include('booking.urls', namespace='booking')),
]

rest/booking/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status_published='published')


class TypeTable(models.Model):
    type = models.CharField('Тип столика', max_length=266)

    def __str__(self):
        return self.type


class Client(models.Model):
    """Данные пользователей, которые хоть раз забронировали столик."""

    name = models.CharField('Имя клиента', max_length=124)
    email = models.CharField('Почта', max_length=124)
    phone = models.CharField('Телефон', max_length=124)

    def __str__(self):
        return 'Забронировано клиентом {}'.format(self.name)


class Table(models.Model):
    """ Данные о бронирований столиков."""

    STATUS_PUBLISHED = (
        ('draft', 'Закрыт для бронирования'),
        ('published', 'Открыт'),
    )
    number = models.IntegerField('Номер', unique=True)
    type = models.ForeignKey(TypeTable, on_delete=models.CASCADE)
    seats = models.IntegerField('Количество стульев')
    booking_price = models.FloatField('Цена бронирования')
    status_booking = models.ForeignKey(Client, on_delete=models.SET_NULL, blank=True, null=True)
    status_published = models.CharField(
        'Доступ к столику',
        max_length=128,
        choices=STATUS_PUBLISHED,
        default='published',
    )

    objects = models.Manager()

    published = PublishedManager()

    def get_absolute_url(self):
        "Метод возвращает с помощью функций reverse() ссылку на cтолик"
        return reverse('booking:table_detail', args=[self.number])

    def __str__(self):
        return 'Столик под номером {}'.format(self.number)

rest/booking/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    phone = forms.IntegerField()

rest/booking/views.py
from django.shortcuts import render, get_object_or_404
from .models import Table, Client
from .forms import EmailPostForm
from django.http import HttpRequest
from .tasks import send_info
from .regular_mail_delivery import regular_send
from django.template.loader import render_to_string
from django.conf import settings


def post_list(request: HttpRequest):
    """
    Возвращаем все столики (вместе с ссылками на бронирование)
    с помощью менеджера published, а так же параметры подбора
    (подбор столика, количество мест, диапазон стоимости)
     """

    tables = Table.published.all()

    # Получает список типов
    types = list(set([str(table.type) for table in tables]))
    # Добавляем вкладку 'все' для отображения всех столиков, ставим его на первое место
    types.insert(0, 'все')

    # Количество стульев
    seats = [int(table.seats) for table in tables]
    seats.sort()

   # Формирование диапазона цены
    prices = [str(table.booking_price) for table in tables]
    prices.sort()

    if tables:
        seats = [str(seats[0]), str(seats[-1])]
        prices = prices[-1]
    # значения по умолчанию для параметра "количество мест" и "стоимость"
    value_range_price = '0'
    seats_table = ''
    if request.method == 'POST':
        type_table = request.POST.get('type_table', '')
        seats_table = request.POST.get('seats_table', '')
        prices_table = request.POST.get('prices_table', '')

        #если в post форме введены данные, мы фильтруем список столиков
        if seats_table:
            tables = tables.filter(seats=seats_table)
        if prices_table != '0':
            tables = tables.filter(booking_price=prices_table)
            value_range_price = prices_table
        if type_table != 'все':
            tables = tables.filter(type__type=type_table)

        # алгоритм, с помощью которого список видов столиков будет всегда выстроен по порядку
        replace_el = types.index(type_table)
        first_el = 0
        types[first_el], types[replace_el] = types[replace_el], types[first_el]

    return render(request, 'booking/post/list.html', {
        'seats_table': seats_table,
        'value_range_price': value_range_price,
        'prices': prices,
        'seats': seats,
        'types': types,
        'tables': tables,
    })


def table_reservation(request, number):
    """
    В этой функций происходит бронирование столика,
    занос данных клиента в базу, и отправка на почту html-формы.
    """
    # Retrieve post by id
    table = get_object_or_404(Table, number=number, status_published='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Если форма валидна, мы идём дальше
            cd = form.cleaned_data

            html_message = render_to_string(
                'booking/email/mail_template.html',
                {
                    'table': table,
                },
                request=request,
            )
            # Если в настройках указано, что должжен быть включен celery, вызывается асинхронная задача
            if settings.STATUS_CELERY == True:
                # вызываем асинхронную задачу
                send_info.delay(html_message, cd['email'])
            else:
                regular_send(html_message, cd['email'])

            sent = True


            # в этом разделе обновляем базу
            client = Client.objects.filter(
                name=cd['name'],
                email=cd['email'],
                phone=cd['phone'],
            )
            # В случае, если клиент ранее не бронировал столик, то создается новая запись
            if not client.exists():
                Client(
                    name=cd['name'],
                    email=cd['email'],
                    phone=cd['phone'],
                ).save()
            # Cтолик теперь с точки зрения БД будет "занят"

            table.status_booking = client.get()
            table.status_published = 'draft'
            table.save()
    else:
        form = EmailPostForm()
    return render(request, 'booking/post/share.html', {'table': table, 'form': form, 'sent': sent})


def table_detail(request, number):
    """
    В этом разделе должна содержаться
    более подробная информация о столике
    """
    return render(request, 'booking/post/detail.html', {'number': number})


def cancel_booking(request, number):
    """
    Отменяет бронирование столика. С точки зрения БД меняет
    статус бронирования на Null, и публикует столик заново
    """

    table = get_object_or_404(Table, number=number, status_published='draft')

    # Пользователь отвязывается от столика
    table.status_booking = None
    table.status_published = 'published'
    table.save()
    return render(request, 'booking/post/cancel_booking.html', {'table': table})

rest/booking/templates/booking/base.html
{% load static %}
<html>
<head><title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="sidebar">
    </div>
</body>
</html>

rest/booking/templates/booking/post/cancel_booking.html
{% block content %}


<h1>Вы отменили бронирование столика</h1>
<p>Надеюсь, мы встретимся ещё!</p>

<p>Номер столика:{{ table.number }}, Тип столика: {{ table.type }}</p>


{% endblock %}

rest/booking/templates/booking/post/detail.html
{% block content %}
  <h1>Это столик под номером {{ number }}</h1>
  <p class="date"> 
    И это прекрасный столик
  </p> 




{% endblock %}

rest/booking/templates/booking/post/list.html
{% extends "booking/base.html" %} {% block title %}My Blog{% endblock %}
{% block content %}

{% load static %}
<html>

<script type="text/javascript">

   function submitForm() {
       console.log ('ааа')
    var selectBox = document.getElementById("input_type_table");
    var selectedValue = selectBox.options[selectBox.selectedIndex].value;
    console.log (selectedValue)
    selectBox.value = selectedValue;
    document.forms["myform"].submit();
   }
</script>

<h1>Столики для бронирования</h1>
<form id="myform" action="#" method="POST">
    {% csrf_token %}
    <label for="input_type_table">Тип столика:</label>

    <select value = '' id="input_type_table" onchange ='submitForm();' name = 'type_table'  >
        {% for type in types %}

        <option value="{{ type }}">{{ type }}</option>


        {% endfor %}

    </select>

    <label for="input_amount">Количество мест:</label>
      <input value ="{{ seats_table }}" type="number" id="input_amount" name="seats_table" min="{{ seats.0 }}" max="{{ seats.1 }}" >
   <label for="input_amount">Стоимость:</label>
    <input value = '{{ value_range_price }}' id='input_price' name = 'prices_table' type="range" min="0" max="{{ prices }}" onchange ='submitForm();'  >
       <label for="input_amount">{{ value_range_price }}</label>


</form>
{% for table in tables %}
<h2>
    <a href="{{ table.get_absolute_url }}"> Номер столика: {{ table.number }} </a>
</h2>
<p class="date">Вид: {{ table.type }}, количество стульев: {{ table.seats }}</p>
<p> <a href="{% url "booking:table_reservation" table.number %}">Забронировать</a> </p>
{{ table.body|truncatewords:30|linebreaks }}


{% endfor %}
{% endblock %}
</html>

rest/booking/templates/booking/post/share.html
{% block content %}

{% if sent %}
    <h1>Вы успешно забронировали столик</h1>
    <p>Данные о бронирований отправлены по адресу {{ form.cleaned_data.email }}.</p>
{% else %}
    <h1>Бронирование столика под номером {{ table.number}}</h1>
    <form action="." method="post">      {{ form.as_p }} {% csrf_token %} <input type="submit" value="Send e-mail">
    </form>
{% endif %}

{% endblock %}